trigger:
  branches:
    include:
      - main

# ---------------- VARIABLES ----------------
variables:
- group: secrets
- name: tag
  value: $(Build.BuildId)

pool:
  name: task-agent

stages:

# ---------------- STAGE 1 ----------------
- stage: Fetch_Source
  displayName: "Checkout Code"
  jobs:
    - job: Checkout
      steps:
        - checkout: self

# ---------------- STAGE 2 ----------------
- stage: SonarQube
  displayName: "Code Quality Analysis"
  dependsOn: Fetch_Source

  jobs:
    - job: Sonar
      displayName: "Run SonarQube Analysis"

      steps:
        - checkout: self
          fetchDepth: 0   # Fix shallow clone issue

        # Prepare SonarQube
        - task: SonarQubePrepare@8
          inputs:
            SonarQube: 'SonarQube Connection'
            scannerMode: 'Other'
            extraProperties: |
              sonar.projectKey=amazon-app
              sonar.projectName=amazon-app
              sonar.sources=Amazon-Core/src,Amazon-Web/src
              sonar.java.binaries=**/target/classes

        # Build + Scan using Maven
        - task: Maven@4
          displayName: "Build and Sonar Scan"
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean verify sonar:sonar'
            options: '-DskipTests=false'

        # Publish Quality Gate result
        - task: SonarQubePublish@8
          inputs:
            pollingTimeoutSec: '300'

# ---------------- STAGE 3 ----------------
- stage: Maven_Build
  displayName: "Build Application"
  dependsOn: SonarQube
  jobs:
    - job: Build
      steps:
        - script: mvn clean package -DskipTests
          displayName: "Build JAR/WAR"

        - script: ls -l target/
          displayName: "Verify Build Output"

        - task: PublishBuildArtifacts@1
          displayName: "Publish Artifacts"
          inputs:
            pathToPublish: target
            artifactName: drop
            publishLocation: Container

# ---------------- STAGE 4 ----------------
- stage: Docker_Build
  displayName: "Build Docker Image"
  dependsOn: Maven_Build
  jobs:
    - job: DockerBuild
      steps:
        - task: DownloadBuildArtifacts@0
          inputs:
            artifactName: drop
            downloadPath: $(Pipeline.Workspace)
        
        - script: |
            echo "Removing old images for this app"
            docker images "$(acrLoginServer)/$(imageName)" --format "{{.Repository}}:{{.Tag}}" | xargs -r docker rmi -f
          displayName: "Cleanup Old App Images"

        - script: |
            docker build -t $(acrLoginServer)/$(imageName):$(tag) .
          displayName: "Build Docker Image"

# ---------------- STAGE 5 ----------------
- stage: Trivy_Scan
  displayName: "Security Scan"
  dependsOn: Docker_Build
  jobs:
    - job: Scan
      steps:
        - script: |
            trivy image --exit-code 0 --severity CRITICAL $(acrLoginServer)/$(imageName):$(tag)
          displayName: "Run Trivy Scan"

# ---------------- STAGE 6 ----------------
- stage: Push_ACR
  displayName: "Push to Azure Container Registry"
  dependsOn: Trivy_Scan
  condition: succeeded()
  jobs:
    - job: Push
      steps:
        - task: Docker@2
          displayName: "Login to ACR"
          inputs:
            containerRegistry: 'ACR-Service'
            command: login

        - script: docker push $(acrLoginServer)/$(imageName):$(tag)
          displayName: "Push Image"

# ---------------- STAGE 7 ----------------
- stage: Deploy
  displayName: "Deploy to AKS"
  dependsOn: Push_ACR
  condition: succeeded()
  jobs:
    - deployment: DeployAKS
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureCLI@2
                displayName: "Connect to AKS"
                inputs:
                  azureSubscription: 'Azure-Service-Connection'
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    az aks get-credentials \
                      --name aks-devops \
                      --resource-group devops-rg \
                      --overwrite-existing

                    az aks update \
                      --name aks-devops \
                      --resource-group devops-rg \
                      --attach-acr $(acrName)

                    kubectl get nodes

              - script: |
                  kubectl apply -f k8s/deployment.yaml
                  kubectl apply -f k8s/service.yaml
                displayName: "Apply Kubernetes Manifests"

              - script: |
                  kubectl set image deployment/amazon-app \
                  amazon-container=$(acrLoginServer)/$(imageName):$(tag)
                displayName: "Update Image"

              - script: |
                  kubectl rollout status deployment/amazon-app
                  kubectl get pods -o wide
                displayName: "Verify Deployment"