apiVersion: apps/v1
kind: Deployment
metadata:
  name: amazon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - name: amazon-container
        image: mydevopsacr.azurecr.io/amazon-app:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always